name: SBOM & Dependency Analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # Этап генерации SBOM
  generate_sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate SBOM
        run: mvn org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom -DincludeTestScope=true -DoutputFormat=xml

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: target/bom.xml
          retention-days: 7

  dependency_check:
    runs-on: ubuntu-latest
    needs: generate_sbom
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull SBOM artifact
        uses: actions/download-artifact@v4
        with:
          name: sbom
          path: ./sbom

      - name: Run OWASP Dependency Check via Docker
        run: |
          mkdir -p dependency-check-report
          docker run --rm \
            -v ${{ github.workspace }}:/src \
            -v ${{ github.workspace }}/dependency-check-data:/usr/share/dependency-check/data \
            owasp/dependency-check:latest \
            --project "Shortener_Service" \
            --scan /src \
            --format HTML \
            --out /src/dependency-check-report

      - name: Upload Dependency Check report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report
          retention-days: 7

  upload_to_dependency_track:
    runs-on: ubuntu-latest
    needs: generate_sbom
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull SBOM artifact
        uses: actions/download-artifact@v4
        with:
          name: sbom
          path: ./sbom

      - name: Upload BOM to Dependency Track
        env:
          DT_URL: ${{ secrets.DEPENDENCY_TRACK_URL }}
          DT_API_KEY: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
        run: |
          curl -X POST "$DT_URL/api/v1/bom" \
               -H "X-Api-Key: $DT_API_KEY" \
               -F "projectName=Shortener_Service" \
               -F "bom=@./sbom/bom.xml"
